export const GamePhase = {
  LOBBY: 'LOBBY',
  CATEGORY_SELECTION: 'CATEGORY_SELECTION',
  INTRO: 'INTRO',
  QUESTION: 'QUESTION',
  ANSWER_REVEAL: 'ANSWER_REVEAL',
  RESULT: 'RESULT',
  DEATH_GAME: 'DEATH_GAME',
  FINAL: 'FINAL',
}
